openapi: 3.0.3
info:
  title: Structurio Auth API
  version: 1.0.0
  description: Nur Check-Email,Try-Login,Register Endpoints
servers:
  - url: http://localhost:8080

paths:
  /auth/check-email:
    post:
      summary: Prüfe ob E-Mail existiert
      operationId: auth_check_email_post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmailRequest'
      responses:
        "200":
          description: Existenzprüfung durchgeführt
      x-openapi-router-controller: openapi_server.controllers.user_controller

  /auth/login:
    post:
      summary: Benutzer einloggen
      operationId: auth_login_post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        "200":
          description: Login erfolgreich
        "401":
          description: Fehlerhafte Daten
      x-openapi-router-controller: openapi_server.controllers.user_controller

  /auth/register:
    post:
      summary: Benutzer registrieren
      operationId: auth_register_post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        "201":
          description: Erfolgreich registriert
        "409":
          description: E-Mail existiert schon
      x-openapi-router-controller: openapi_server.controllers.user_controller

components:
  schemas:
    EmailRequest:
      type: object
      required: [email]
      properties:
        email:
          type: string
          format: email
          example: max@example.com

    LoginRequest:
      type: object
      required: [email, password]
      properties:
        email:
          type: string
          format: email
          example: max@example.com
        password:
          type: string
          format: password
          example: pass123

    RegisterRequest:
      type: object
      required: [surname, lastname, email, password, birthdate]
      properties:
        surname:
          type: string
        lastname:
          type: string
        email:
          type: string
          format: email
          example: max@example.com
        password:
          type: string
          format: password
          example: pass123
        birthdate:
          type: string
          format: date
          example: 2005-04-01