openapi: 3.0.3
info:
  title: Structurio Auth API
  version: 1.0.0
  description: Nur Check-Email Endpoint
servers:
  - url: http://localhost:8080

paths:
  /auth/check-email:
    post:
      summary: Prüfe ob E-Mail existiert
      operationId: auth_check_email_post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmailRequest'
      responses:
        "200":
          description: E-Mail gefunden
        "404":
          description: E-Mail nicht vorhanden
      x-openapi-router-controller: openapi_server.controllers.user_controller

components:
  schemas:
    EmailRequest:
      type: object
      required: [email]
      properties:
        email:
          type: string
          format: email
          example: max@example.com